sudo: require
services:
  - docker

before_install:
  - docker build -t ronakchhatbar/docker-react -f Dockerfile.dev .

script:
  - docker run ronakchhatbar/docker-react npm run test -- --coverage
  
