sudo: require
services:
  - docker

before_install:
  - docker build -t ronakchhatbar/docker-react -f Dockerfile.dev .

script:
  - docker run ronakchhatbar/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-404148944045"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_key
  secret_access_key:
    secure: $AWS_secrete_key

